file

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,10 +1,10 @@
-#!/usr/bin/env bash
-#script 
+#!/bin/bash
+# Define the PID file location
 PID_FILE="/var/run/myscript.pid"
 echo $$ > "$PID_FILE"
-trap 'echo "I hate the kill command"' SIGTERM
-trap 'echo "Y U no love me?!"' SIGINT
-trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM
+trap 'echo "I hate the kill command"' SIGTERM  # Display message but do not exit
+trap 'echo "Y U no love me?!"' SIGINT  # Display message on Ctrl+C
+trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM  # Cleanup on SIGQUIT or SIGTERM and exit
 while true
 do
     echo "To infinity and beyond"
